- hosts: mssql 
  remote_user: root
  tasks:
    - name: curl -o 
      shell: curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo
    - name: install mssql
      shell: yum install -y mssql-server
